---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnetcorewebapp
  labels:
    app: dotnetcorewebapp
    visualize: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnetcorewebapp
        visualize: "true"
    spec:
      containers:
      - name: dotnetcorewebapp
        image: structura/dotnetcorewebapp:latest
        ports:
        - name: web
          containerPort: 5555
          hostPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetcorewebapp
spec:
  selector:
    app: dotnetcorewebapp
  ports:
  - name: http
    port: 5555
    targetPort: 5555
    nodePort: 30555
  type: NodePort